name: Testing workflow

on: [push, pull_request]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .
