name: Testing workflow

on: [push, pull_request]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name : "Install libraries required to run pytest on diffusion code"
        run : pip install numpy matplotlib
      - name : "Install pytest"
        run: pip install -U pytest
      - name : "Install coverage"
        run: pip install -U coverage
      - name: "Run pytest"
        run: python -m pytest
      - name: "Run converge"
        run: coverage run -m pytest
      - name: "Adding report to .coverage location"
        uses: actions/upload-artifact@v2
        with:
          name: Coverage Report
          path: .coverage
          retention-days: 1
               
  
